# Generated by Django 5.2.3 on 2025-06-30 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iotmonitor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='value',
            field=models.FloatField(),
        ),
    ]
